### ISSUE TITLE
Single-Player mode

### ISSUE THREAD

**Issue by masashi-hatano** [Tomoya-Matsubara/Multiplayer-AR-Shooting-Game#1]
Objective:
Develop a single-player mode: we are gonna work on feature/single-player branch.

TODO:
- [x] Create a marker and display multiple targets based on the marker.
- [x] Display something like bullet when screen was tapped.
- [x] Create a scoring function and display it in the latest state.

Others:
We would like to develop a single-player mode like [this video](https://www.youtube.com/watch?v=YZvKZ3QpMF4), I hope this helps you understand well.

**Comment by masashi-hatano** [comment]
I'm taking care of the third item in TODO list.

What I've done so far is:
- Create moving sphere (assuming that this is a bullet) at constant velocity.
- If the bullet is traveled more than a specific distance, then it is deleted from the scene.
- Add function: CollisionJudge.cs using OnCollisionEnter.

Issue:
Vuforia marker and its object exist in the beginning, but they disappear when I executed.
-> I wasn't able to test if CollisionJudge works or not.

**Comment by Tomoya-Matsubara** [comment]
I finished implementing the functionality of spawning target objects based on the detected marker.

<ul>
<li>A new target object is instantiated every 2 seconds</li>
<li>The position where target objects are generated is random</li>
<li>The angle of target objects is also random</li>
<li>Each target object gradually fades out and is destroyed after the lifespan</li>
<li>With a 10% probability, a golden target object appears</li>
<ul>
<li>Its lifespan is short</li>
<li>It can be used as a special target (e.g., a higher score is assigned)</li>
</ul>
</ul>

**Comment by Tomoya-Matsubara** [comment]
**FAQ: How to get ARCamera's positions?**

ARCamera is a <code>GameObject</code>. The position can be obtained in the following way:
```c#
GameObject arCamera = GameObject.Find("ARCamera");
Vector3 position = arCamera.transform.position;
```

There is a related post in the [Vuforia's Community Forum](https://developer.vuforia.com/forum/unity-extension-technical-discussion/arcamera-position?sort=2).

**Comment by Tomoya-Matsubara** [comment]
##  2. Display something like bullet when screen was tapped.

The function to fire a bullet when the screen is tapped has already been implemented. 

Currently, there is

- A button that fires a bullet when tapped
- A script that fires a bullet in the direction along the ray from the camera to the tapped position on the screen

In my opinion, the latter one is probably better.

## 3. Create a scoring function and display it in the latest state.

The scoring function has already been implemented.

The player gets 

- 50 points when a bullet collides with a normal target
- 500 points when a bullet collides with a special target

**Comment by Tomoya-Matsubara** [comment]
Now that the three fundamental features have been implemented, I close this issue.
